### PR TITLE
Setting Main window and Configuration window names

### PR DESCRIPTION
**Pull request by ntrp**
As you requested I am sending window names changes to you.

### CODE REVIEW

**Comment by lanoxx** [comment]
Before merging these changes I would like to know:

a) If any distribution is currently pulling from this repo
b) If anyone still requires tilda to work with GTK+2

The new code does not contain GTK+2 compatibility code. So for the time being the tsloughter/master will be the legacy GTK+2 code and my lanoxx/master repo will be the GTK+3 code base.

**Comment by ntrp** [comment]
Ah I am sorry. Didn't intend to pull request all the changes.. I thought that only mine changes would figure in the merge request.

**Comment by lanoxx** [comment]
The changes are specific to GTK+3 in GTK+2 the Styling was handled differently, so we cannot merge only your patch to this repo.

Im thinking to branch the tsloughter/main into a tsloughter/legacy branch and then merging everything to master, what do you think Tristan? We could then maybe cherry pick a few fixes to the legacy branch and do a bugfix release.

**Comment by tsloughter** [comment]
Shit, I never replied to this. @lanoxx that sounds perfect. Thanks.

**Comment by lanoxx** [comment]
Hey Tristan,

no problem. I was also busy in the mean time. There is now a new tilda package in Debian experimental (tilda/1.1.5-1). Yesterday I uploaded 1.1.7-1 to mentors which should be sponsored soon. At least for Debian I have now entered my repo as the main repo, so Im not sure if it still makes sense to merge the changes back. Do you know if any distribution is pulling releases from your repository?

**Comment by tsloughter** [comment]
There is no distro pulling releases from my repo as far as I know.

**Pull request closed without merging**
